extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_0[201];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_DieLava_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_DieLava_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_DieLava_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Hard_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Hard_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Hard_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_QuickSand_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_QuickSand_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_QuickSand_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_004[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_004[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_005[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_005[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_003[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_003[];
extern Gfx mat_castle_grounds_dl_sm64_water_mat[];
extern Gfx mat_revert_castle_grounds_dl_sm64_water_mat[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1[];
extern Gfx castle_grounds_dl_DieLava_mesh_layer_1[];
extern Gfx castle_grounds_dl_Hard_mesh_layer_1[];
extern Gfx castle_grounds_dl_QuickSand_mesh_layer_1[];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_1[];
